"""
SQLAlchemy ORM models for LLM-generated insights and forecast results.

Tables:
  - insights         : LLM-generated textual summaries per entity
  - forecast_results : Statistical trend forecasts per entity
"""

from __future__ import annotations

import uuid
from datetime import date, datetime, timezone
from typing import Any, Dict, Optional

from sqlalchemy import (
    Date,
    DateTime,
    Enum,
    Float,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from backend.db.database import Base
from backend.models.trend_signal import EntityType


# ---------------------------------------------------------------------------
# Insight
# ---------------------------------------------------------------------------


class Insight(Base):
    """
    An LLM-generated textual insight for a research entity.

    One row per (entity_id, llm_model, created_at) — multiple insight
    versions can be stored to track quality over time or model upgrades.

    Attributes:
        id:            UUID primary key.
        entity_id:     UUID of the related Paper, Repository, or Topic row.
        entity_type:   Discriminator (paper | repository | topic).
        insight_text:  Full natural-language insight generated by the LLM.
        insight_type:  Category of insight (summary | analysis | comparison | forecast_narrative).
        llm_model:     Model identifier used for generation (e.g. "gpt-4o-mini").
        prompt_tokens: Number of prompt tokens consumed.
        completion_tokens: Number of completion tokens generated.
        tokens_used:   Total token count (prompt + completion).
        created_at:    Generation timestamp (UTC).
    """

    __tablename__ = "insights"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    entity_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="UUID of the related entity",
    )
    entity_type: Mapped[EntityType] = mapped_column(
        Enum(EntityType, name="entity_type_enum", create_constraint=False),
        nullable=False,
        index=True,
    )
    insight_text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="LLM-generated insight text",
    )
    insight_type: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        default="summary",
        comment="summary | analysis | comparison | forecast_narrative | daily_digest",
    )
    llm_model: Mapped[str] = mapped_column(
        String(128),
        nullable=False,
        comment="LLM model identifier used for generation",
    )
    prompt_tokens: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
    )
    completion_tokens: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
    )
    tokens_used: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="Total tokens consumed (prompt + completion)",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        index=True,
    )

    __table_args__ = (
        Index("ix_insights_entity_created", "entity_id", "entity_type", "created_at"),
        Index("ix_insights_type_created", "insight_type", "created_at"),
        {"comment": "LLM-generated insights for papers, repositories, and topics"},
    )

    def __repr__(self) -> str:
        return (
            f"<Insight entity_id={self.entity_id!s:.8s} "
            f"model={self.llm_model} created={self.created_at}>"
        )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": str(self.id),
            "entity_id": str(self.entity_id),
            "entity_type": self.entity_type.value,
            "insight_text": self.insight_text,
            "insight_type": self.insight_type,
            "llm_model": self.llm_model,
            "prompt_tokens": self.prompt_tokens,
            "completion_tokens": self.completion_tokens,
            "tokens_used": self.tokens_used,
            "created_at": self.created_at.isoformat(),
        }


# ---------------------------------------------------------------------------
# ForecastResult
# ---------------------------------------------------------------------------


class ForecastResult(Base):
    """
    A statistical trend forecast for one entity at a specific future date.

    Stores the point prediction and confidence interval produced by the
    forecasting model (e.g. Prophet, ARIMA, or a custom neural model).

    One row per (entity_id, forecast_date, model_used).

    Attributes:
        id:               UUID primary key.
        entity_id:        UUID of the entity being forecast.
        entity_type:      Discriminator (paper | repository | topic).
        forecast_date:    The future date this prediction is for.
        predicted_value:  Point estimate of the trend score on forecast_date.
        confidence_lower: Lower bound of the 95% confidence interval.
        confidence_upper: Upper bound of the 95% confidence interval.
        model_used:       Model identifier (e.g. "prophet", "arima", "lstm").
        horizon_days:     Number of days ahead from computation date.
        created_at:       When the forecast was computed.
    """

    __tablename__ = "forecast_results"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    entity_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="UUID of the entity being forecast",
    )
    entity_type: Mapped[EntityType] = mapped_column(
        Enum(EntityType, name="entity_type_enum", create_constraint=False),
        nullable=False,
        index=True,
    )
    forecast_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        index=True,
        comment="Future calendar date this prediction is for",
    )
    predicted_value: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Point estimate of the trend score",
    )
    confidence_lower: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
        comment="Lower 95% confidence interval bound",
    )
    confidence_upper: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
        comment="Upper 95% confidence interval bound",
    )
    model_used: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        default="prophet",
        comment="Forecasting model identifier",
    )
    horizon_days: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="Days ahead from the computation date",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        index=True,
    )

    __table_args__ = (
        Index("ix_forecast_entity_date", "entity_id", "forecast_date"),
        Index("ix_forecast_entity_type_date", "entity_type", "forecast_date"),
        Index("ix_forecast_predicted_desc", predicted_value.desc()),
        {"comment": "Statistical trend forecasts per entity and future date"},
    )

    def __repr__(self) -> str:
        return (
            f"<ForecastResult entity_id={self.entity_id!s:.8s} "
            f"date={self.forecast_date} value={self.predicted_value:.4f}>"
        )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": str(self.id),
            "entity_id": str(self.entity_id),
            "entity_type": self.entity_type.value,
            "forecast_date": self.forecast_date.isoformat(),
            "predicted_value": self.predicted_value,
            "confidence_lower": self.confidence_lower,
            "confidence_upper": self.confidence_upper,
            "model_used": self.model_used,
            "horizon_days": self.horizon_days,
            "created_at": self.created_at.isoformat(),
        }
